### ISSUE TITLE
rotated images in Tropy

### ISSUE THREAD

**Issue by atomotic** [martimpassos/tropy-export-iiif#19]
Images [can be rotated](https://docs.tropy.org/in-the-item-view/photo-editing) in Tropy, which sets the `angle` value in the `images` table of the SQLite database. 

```
sqlite> select * from images where angle<>0;
id  width  height  angle  mirror  brightness  contrast  hue  saturation  negative  sharpen
--  -----  ------  -----  ------  ----------  --------  ---  ----------  --------  -------
8   1295   2569    270    0       0           0         0    0           0         0
38  2480   3508    270    0       0           0         0    0           0         0
40  2480   3508    90     0       0           0         0    0           0         0
50  1164   3501    270    0       0           0         0    0           0         0
52  1164   3501    270    0       0           0         0    0           0         0
56  2480   3508    270    0       0           0         0    0           0         0
58  2480   3508    90     0       0           0         0    0           0         0
76  2480   3507    270    0       0           0         0    0           0         0
```

However, the exported IIIF from Tropiiify doesn't preserve this rotation.
This issue could potentially be addressed using an [Image Service Rotation](https://iiif.io/api/cookbook/recipe/0040-image-rotation-service/)

**Comment by martimpassos** [comment]
Hi Raffaele, thanks for pointing this out! Since tropiiify exports a level0/static collection, I'm not sure a service like this would work (maybe CSS would, but it is viewer-dependent). I can, however, apply the rotation to the images before tiling and exporting them.

**Comment by martimpassos** [comment]
0.3.2 should fix this
