### ISSUE TITLE
Issue with TIFF files

### ISSUE THREAD

**Issue by atomotic** [martimpassos/tropy-export-iiif#20]
I have encountered an issue while using the IIIF Manifest plugin with a Tropy collection containing TIFF files. The exported manifest's `thumbnail` links point to full-resolution tiles that are not converted to JPEG format as expected.

Example from manifest:

```json
"thumbnail": [
                {
                    "id": "https://grafton9.net/tpo/01903639f5c97396a6b54bd81a5a161a/10dfcd97692e5a5a2fa2d7d454f9e027/full/206,300/0/default.tif",
                    "type": "Image",
                    "format": "image/tiff",
                    "height": 300,
                    "width": 206
                }
            ],
```

Directory structure:
```
│   ├── full
│   │   ├── 1088,1581
│   │   │   └── 0
│   │   │       └── default.tif
│   │   └── 206,300
│   │       └── 0
│   │           └── default.tif
```

File analysis
```
$ mediainfo full/206,300/0/default.tif
General
Complete name                            : full/206,300/0/default.tif
Format                                   : TIFF
File size                                : 13.3 KiB

Image
Format                                   : JPEG (ISO)
Format settings                          : Little
Width                                    : 206 pixels
Height                                   : 300 pixels
Color space                              : YUV
Bit depth                                : 8 bits
Density                                  : 25.400 dpi
```

I will investigate the plugin's code to understand why the conversion to JPEG isn't happening as expected. I aim to contribute to fixing this issue.
Thanks!

**Comment by martimpassos** [comment]
Ciao Raffaele, in this case you'd expect the thumbnail to be a JPEG and the midsize image a tiff?

**Comment by atomotic** [comment]
If I'm not mistaken, I would expect all jpgs for thumbnails.
This is the full context: a [Tropiify exported collection viewed with Canopy](https://grafton9.net/tpo/search)
and it doesn't work because the `thumbnails` are TIFFs.

But, fun fact, it works in Safari (macos) because it renders TIFFs  🤯
<img width="931" alt="Screenshot 2024-07-10 at 20 09 30" src="https://github.com/arkalab/tropiiify/assets/67420/06f9e22e-6ed6-4562-bde0-efe849bf5162">

**Comment by atomotic** [comment]
Ciao Martim. The `0.3.2` release seems not containing the merged PR. I have installed on a new Tropy installation on another desktop (I will look better by end of the day)

**Comment by martimpassos** [comment]
My bad, I messed up the merge of your contribution with the rotation/mirroring fix. Should be good now! (I deleted the release so it's still 0.3.2, give it a go)

**Comment by martimpassos** [comment]
Hi @atomotic, have you done further testing/work? Is everything working all right for you?

**Comment by atomotic** [comment]
I haven't used TIFFs files since last summer, but the last collection I published with Tropiiify was working.
