### ISSUE TITLE
Homepage property not added to manifest

### ISSUE THREAD

**Issue by buccalon** [martimpassos/tropy-export-iiif#23]
### Expected behavior
I'd like to add a link to the holding institution using the [homepage](https://iiif.io/api/presentation/3.0/#homepage) property.

### Bug description

The exported manifest does not contain the homepage link.

I used the following config:

- homepage label (plugin settings): "Mais informações"
- homepage:id property (template settings): foaf:homepage
- homepage:id value (item metadata): https://brasilianafotografica.bn.gov.br/brasiliana/handle/20.500.12156.1/6743

**Comment by martimpassos** [comment]
Solved in v0.3.3
